version = "1"

[main]
name.fr = "Configuration"
name.en = "Main configuration"
help = ""
services = ["saltcorn"]

[main.main]
name = "Authentification"
[main.main.registration]
ask.en = "Enable visitor's registration"
ask.fr = "Autoriser les visiteurs à créer un compte"
help.en = "When selected allow visitors to create an account from the login screen."
help.fr = "Si activé, les visiteurs pourront créer un compte depuis la page de login."
type = "boolean"
default = 0
yes = "true"
no = "false"

[main.main.ldap]
ask.fr = "Autoriser la connexion aux utilisateurs LDAP yunohost"
ask.en = "Allow yunohost LDAP users to authenticate"

type = "boolean"
yes = "true"
no = "false"


[main.limit_size]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

[main.limit_size.upload_max_size]
ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
ask.en = "Size limit file upload (Mb)"
type = "number"
bind = "null"
