packaging_format = 2

id = "saltcorn"
name = "Saltcorn"
description.en = "Open source no-code database application builder"
description.fr = "Application no-code de création d’applications de base de données."

version = "1.3.1~ynh2"

maintainers = ["otm33GH"]

[upstream]
license = "MIT"
website = "https://saltcorn.com/"
admindoc = "https://wiki.saltcorn.com"
code = "https://github.com/saltcorn/saltcorn"

[integration]
yunohost = ">= 12.1.6"
architectures = "all"
helpers_version = "2.1"
multi_instance = false

ldap = true
sso = false

disk = "2000M"
ram.build = "1500M"
ram.runtime = "1500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    
    [install.admin]
    type = "user"
    
    [install.admin_pw]
    ask.en = "Please chose a password for the admin user."
    ask.fr = "Choisissez un mot de passe pour l'administrateur."
    type = "password"

    [install.registration]
    ask.en = "Do you want to enable visitor's registration ?"
    ask.fr = "Voulez-vous autoriser les visiteurs à s'inscrire sur votre application ?"
    type = "boolean"
    default = "true"
    yes = "true"
    no = "false"

    [install.ldap]
    ask.en = "Do you want to enable ldap authentication ?"
    ask.fr = "Voulez-vous autoriser l'authentification LDAP ?"
    type = "boolean"
    default = "true"
    yes = "true"
    no = "false"
    
[resources]    
    [resources.sources.main]
    url = "https://github.com/saltcorn/saltcorn/archive/refs/tags/v1.4.0.tar.gz" 
    sha256 = "9000457c8386587bda419a1b0c60452ef4f7a98cd50705fb0629f45ae30f79d6"
    autoupdate.strategy = "latest_github_tag"
    autoupdate.assets = "tar.gz"
    
    [resources.system_user]

    [resources.install_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, libpq-dev, build-essential, python-is-python3,libcap2-bin libsystemd-dev"

    [resources.data_dir]    
    subdirs = ["backups"]
    group = "www-data:rx"
    
    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"


